/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-24 01:13:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import ssg.com.a.dto.stockParam;
import ssg.com.a.dto.stocksDto;
import java.util.List;

public final class stockMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ssg.com.a.dto.stocksDto");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("ssg.com.a.dto.stockParam");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");

   List<stocksDto> list = (List)request.getAttribute("stocklist"); 
   stockParam param = (stockParam)request.getAttribute("param");
   List<ArrayList> slist = (List)request.getAttribute("slist");
   List<ArrayList> sslist = (List)request.getAttribute("sslist");
   List<ArrayList> ssslist = (List)request.getAttribute("ssslist");
   String choice = param.getChoice();
   String search = param.getSearch();
   

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>stockmain</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("<select id=\"choice\">\r\n");
      out.write("	<option value=\"Name\">종목명</option>\r\n");
      out.write("	<option value=\"Symbol\">종목번호</option>\r\n");
      out.write("	<input type=\"text\" value=\"\"  id=\"search\" >\r\n");
      out.write("	<button type=\"button\"  onclick=\"searchBtn()\">검색</button>\r\n");
      out.write("</select>\r\n");
      out.write("<table border=\"1\"  id=\"capsc\">\r\n");
      out.write("	<thead>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td colspan=\"5\">\r\n");
      out.write("				<input type=\"button\" id=\"count\" value=\"거래량 100위\">\r\n");
      out.write("			</td>\r\n");
      out.write("			<td colspan=\"7\">\r\n");
      out.write("				<input type=\"button\" id=\"cap\" value=\"시가총액 100위\">\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<th>NO.</th><th>종목명</th><th>현재가</th><th>전일비</th><th>등락률</th><th>거래량</th><th>거래대금</th><th>매수호가</th><th>매도호가</th><th>시가총액</th><th>PER</th><th>ROE</th>		\r\n");
      out.write("	</thead>\r\n");
      out.write("	<tbody>		\r\n");
      out.write("			<tr>\r\n");
      out.write("				");
      out.print(sslist.get(0));
      out.write("\r\n");
      out.write("				");
      out.print(ssslist.get(0) );
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("	</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table border=\"1\" id=\"countsc\" style=\"display: none;\">\r\n");
      out.write("	<thead>		\r\n");
      out.write("	</thead>\r\n");
      out.write("	<tbody>		\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td colspan=\"5\">\r\n");
      out.write("				<input type=\"button\" id=\"count1\" value=\"거래량 100위\">\r\n");
      out.write("			</td>\r\n");
      out.write("			<td colspan=\"7\">\r\n");
      out.write("				<input type=\"button\" id=\"cap1\" value=\"시가총액 100위\">\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	\r\n");
      out.write("			<tr>\r\n");
      out.write("				");
      out.print(slist.get(0) );
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("	</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 거래량 시가총액 하나씩 보게 하기 위함 -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("		\r\n");
      out.write("	$(\"#cap\").click(function() {	\r\n");
      out.write("		$(\"#capsc\").show();\r\n");
      out.write("		$(\"#countsc\").hide();\r\n");
      out.write("	}); \r\n");
      out.write("	\r\n");
      out.write("	 $(\"#count\").click(function() {\r\n");
      out.write("		$(\"#capsc\").hide();\r\n");
      out.write("		$(\"#countsc\").show();\r\n");
      out.write("	});\r\n");
      out.write("	 \r\n");
      out.write("	 $(\"#cap1\").click(function() {	\r\n");
      out.write("			$(\"#capsc\").show();\r\n");
      out.write("			$(\"#countsc\").hide();\r\n");
      out.write("		}); \r\n");
      out.write("		\r\n");
      out.write("		 $(\"#count1\").click(function() {\r\n");
      out.write("			$(\"#capsc\").hide();\r\n");
      out.write("			$(\"#countsc\").show();\r\n");
      out.write("		});\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
